### ISSUE TITLE
uboot seems to boot at a different baud rate than the kernel

### ISSUE THREAD

**Issue by dtkerns** [m01/rock64-arch-linux-build#10]
via usb serial console connection, all I get is junk until the kernel is running
I've connected @ 9600, 38400, 57600 and 115200 ... only 38400 after the kernel has started results in good comms

**Comment by m01** [comment]
I don't remember having issues with this; did you try 1.5M as explained here? https://forum.pine64.org/showthread.php?tid=5029

**Comment by dtkerns** [comment]
nope ... but I will. thanks!

**Comment by m01** [comment]
Did you have any luck?

**Comment by m01** [comment]
I'm going to close this issue as presumably fixed by using the baud rate specified in the link mentioned above, but please reopen it if you think there's an issue with code in this repo.
