### ISSUE TITLE
Dockerfile to build the image

### ISSUE THREAD

**Issue by picodotdev** [m01/rock64-arch-linux-build#4]
I have written a Dockerfile with which it seems possible to build the image.

The benefits of using Docker are:

* Reproducible constructions, no problems due to the environment of the own system
* Not install the necessary build tools in own system
* Use the environment of other distributions different from the own (Debian, Ubuntu, Arch Linux, ...)
* Allow Windows users and macOS to build the image
* The Dockerfile serves as documentation for how to install the build tools and the build commands

I have not tested it completely because of #3.

```
# Dockerfile
FROM pritunl/archlinux:latest

RUN echo "" >> /etc/pacman.conf
RUN echo "[archlinuxfr]" >> /etc/pacman.conf
RUN echo "SigLevel=Optional TrustAll" >> /etc/pacman.conf
RUN echo "Server=http://repo.archlinux.fr/\$arch" >> /etc/pacman.conf

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm base-devel aarch64-linux-gnu-gcc dtc git uboot-tools swig openssh yaourt

RUN useradd -m -G wheel -s /bin/bash albi
RUN sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
RUN su - albi -c "yaourt -Sy --noconfirm --needed libguestfs"

RUN su - albi -c "git clone https://github.com/m01/rock64-arch-linux-build.git"
RUN pacman -S --noconfirm python-virtualenv
RUN su - albi -c "(cd rock64-arch-linux-build && make arch.img)"

# build.sh
#!/usr/bin/env bash
docker build -t picodotdev/archlinuxarm-rock64:latest .
docker run --rm picodotdev/archlinuxarm-rock64:latest "cat /home/albi/rock64-arch-linux-build/arch.img" > arch.img
```

**Comment by m01** [comment]
Hi there,
Thank you for your suggestion!

I think it's worth getting the build fixed first (#3), as that may change what the `Dockerfile` needs to look like..

In the meantime, I'm curious about a couple of things in your suggested `Dockerfile`:

* I noticed the Arch Linux wiki [suggests](https://wiki.archlinux.org/index.php/Docker#Images) using `FROM: archlinux/base`, what's the advantage of `pritunl/archlinux`?
* Is there an advantage in using the `docker run ... cat ...` over using mounts or `docker cp`? (I've just not come across your method yet)
* Is there a story behind the username `albi`? :slightly_smiling_face:

**Comment by picodotdev** [comment]
* I searched a Arch Linux docker image in the hub and I found base/archlinux and in it's docker file has `ADD archlinux-2014.07.03.tar.xz /` that seems to be outdated, I picked another Arch Linux image, but yes as the wiki says better use archlinux/base.
* The `docker cp` documentation states that is for containers and I wanted to extract a file from a docker image
* albi is the name that I used for a user, albi == Arch Linux Build Image, but any other name can be used

**Comment by m01** [comment]
Thank you for answering my questions!
I read a bit more about the difference between `pritunl/archlinux` and `archlinux/base` (they're both actually mentioned on the Arch Linux wiki), and I think it's better to use `archlinux/base` here, since I don't think we don't need to use a snapshot of the Arch Linux repository from the day the docker image was built (do let me know if you disagree!). In general I prefer using "official" images over third party ones, if at all possible. I looked at the Dockerfile in the https://github.com/archlinux/archlinux-docker repo, and it indeed adds a `tar` file, but I believe that `tar` file is generated when `make` is run, so I think it's OK (there's no hardcoded date as far as I can see).

I didn't notice earlier that building the `arch.img` Rock64 image was actually done as part of the `docker build` step. I think it would be better to build a "builder" docker container which can then be used (if necessary, repeatedly) to build the Rock64 image; I think this might help with troubleshooting, and later if we want to build other packages as well. What do you think?

In general, would you prefer to create a fork of the repo and file a pull request with your Dockerfile, or would you like me to take inspiration from your Dockerfile, make it build the image completely and merge it? I'd add you to the credits in the README in either case (I'm still planning on eventually upstreaming the Arch build scripts into ayufan's code when they're ready for it, at which point much of this may change).

**Comment by picodotdev** [comment]
I agree with all points, I will use `archlinux/base` and I will create a builder image. Give me some time and I will try to send a pull request.

**Comment by m01** [comment]
Sounds good!

**Comment by nsollars** [comment]
Using docker are you able to add configurable items like dtb changes?.  My requirement needs the SPI gpio not the SPI flash so id like it auto disabled.

I was hoping this flexibility would be an option so I would not have to do so many manual steps.

**Comment by ejprice** [comment]
With Docker, you could keep the source tree external to the docker container and mount it during container runtime. I believe this is how Armbian does it with their vagrant builds. It might be a little cleaner separation this way as it would enable customizations prior to running the container which does the actual building.

**Comment by picodotdev** [comment]
I will try to use a volume for allow customizations. Give me some more time. Thanks for the suggestions!.

**Comment by nsollars** [comment]
@picodotdev Surething,  please reach out out if you need help or perhaps a tester..

Nige

**Comment by picodotdev** [comment]
I refactored the docker builder image to allow personalize the build using a volume and externalizing the git repositories.

I have found this errors building the arch.img on a mac that I think is related to have a filesystem case insensitive. Also https://github.com/ayufan-rock64/linux-u-boot has https://github.com/ayufan-rock64/linux-u-boot/blob/rockchip-master/scripts/Kconfig and https://github.com/ayufan-rock64/linux-u-boot/tree/rockchip-master/scripts/kconfig that could cause problems.

```
make -C u-boot KBUILD_OUTPUT=/rock64-arch-linux-build/tmp/u-boot-rock64 BL31= CROSS_COMPILE="aarch64-linux-gnu-" rock64-rk3328_defconfig
make[1]: Entering directory '/rock64-arch-linux-build/u-boot'
make[2]: Entering directory '/rock64-arch-linux-build/tmp/u-boot-rock64'
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
input in flex scanner failed
make[3]: *** [/rock64-arch-linux-build/u-boot/scripts/kconfig/Makefile:121: rock64-rk3328_defconfig] Error 2
make[2]: *** [/rock64-arch-linux-build/u-boot/Makefile:478: rock64-rk3328_defconfig] Error 2
make[2]: Leaving directory '/rock64-arch-linux-build/tmp/u-boot-rock64'
make[1]: Leaving directory '/rock64-arch-linux-build/u-boot'
make[1]: *** [Makefile:150: sub-make] Error 2
make: *** [Makefile.uboot.mk:7: tmp/u-boot-rock64/.config] Error 2
```

I don't tested it, currently only I have a mac. @nsollars, Could you test in a Linux system?

**Comment by nsollars** [comment]
Yes I can,

Give me some time to create a clean Arch linux VM and il report back as soon as possible.

Nige

**Comment by nsollars** [comment]
@picodotdev  Could you link the docker image,  just to be consistent.  Went back through the thread here and it did not look obvious ;).

Ive got a clean Arch linux ready for this one..
Nige

**Comment by picodotdev** [comment]
@nsollars link the docker image? I don't understand. This? https://github.com/m01/rock64-arch-linux-build/pull/6

Build your own docker builder image with `docker-build.sh`and the `arch.img` with `build-image.sh`.

**Comment by nsollars** [comment]
Yeah that would be it, I was looking for the .sh files and what the latest rev was.

**Comment by m01** [comment]
Regarding case insensitive filesystem issues on macOS: When [building the Android source code on macOS, the docs suggest creating a case-insensitive disk image for the builds](https://source.android.com/setup/initializing#setting-up-a-mac-os-x-build-environment). Might be worth a shot.

**Comment by nsollars** [comment]
Alright so after running both docker-build.sh and build.image.sh,

I have the following image:
                                            2.1G    arch.img

So for me on a vanilla arch vbox vm the build seems to be successful.

**Comment by m01** [comment]
I've added some comments on the PR, I'm looking forward to merging the code.

**Comment by nsollars** [comment]
Comments look reasonable,  looks like fun times ahead

**Comment by m01** [comment]
PR #6 is merged and the README is updated, thank you @picodotdev for raising the issue, filing the PR and addressing all the comments, and thank you @nsollars and @ejprice for your comments and testing!
