### ISSUE TITLE
No HDMI Signal

### ISSUE THREAD

**Issue by d3nw0** [m01/rock64-arch-linux-build#8]
So I installed/burned this [image](https://github.com/m01/rock64-arch-linux-build/releases/download/v0.1/arch.img.xz) onto my micro SD CARD. Then I booted my rock64, but nothing happend. I restarted the rock64 and my mouse and keyboard lit up but my monitor didn't catch a signal.

Also I did install uboot using this [guide](http://wiki.pine64.org/index.php/NOOB#Using_a_Stand-Alone_Image_to_Write_u-boot_to_SPI).

Any ideas?

**Comment by m01** [comment]
This is currently expected (there's a known issue note on the release page). I've not tested anything but a headless setup, and don't expect there to be any display drivers in the image for the Rock64.

Unfortunately, ARM doesn't (AFAIK) release their graphics drivers under permissible licenses. :slightly_frowning_face: 

If anyone wants to have a play nevertheless, I'd start from ayufan's graphics driver repo here for the Rock64: https://github.com/ayufan-rock64/libmali, look at some of the package build scripts for Mali drivers for some of the other platforms that are hosted in the `alarm` repo and try to come up with some package build scripts for the graphics drivers. I don't know whether there would be any dependency on the kernel.

**Comment by d3nw0** [comment]
I didn't notice that. Sorry for the inconvenience.
