### ISSUE TITLE
[NOT A BUG] Rock64 page appeared on the ArchLinux ARM website

### ISSUE THREAD

**Issue by s-kostyuk** [m01/rock64-arch-linux-build#9]
So, here is the link: https://archlinuxarm.org/platforms/armv8/rockchip/rock64. I didn't tested this image yet and further didn't compare the mentioned image with provided in this (m01) repository.

But anyway, it's present now

**Comment by rontant** [comment]
The steps outlined in the official Arch Linux Arm website work fine.  The only issue I found so far is that USB 3.0 hub/drive not working.

**Comment by m01** [comment]
It's great that there are now some more official instructions on running Arch Linux on a Rock64!
I'll add a note to the `README` to point people there, as many may prefer that option.
